version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: matrix_mlm_db
    environment:
      POSTGRES_DB: matrix_mlm
      POSTGRES_USER: matrix_user
      POSTGRES_PASSWORD: matrix_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - matrix_network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: matrix_mlm_backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://matrix_user:matrix_password@postgres:5432/matrix_mlm
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 3001
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - matrix_network
    restart: unless-stopped

  # Admin Panel
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: ../Dockerfile.admin
    container_name: matrix_mlm_admin
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      REACT_APP_WS_URL: ws://localhost:3001
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - matrix_network
    restart: unless-stopped

  # User Panel
  user-panel:
    build:
      context: ./user-panel
      dockerfile: ../Dockerfile.user
    container_name: matrix_mlm_user
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      REACT_APP_WS_URL: ws://localhost:3001
    ports:
      - "3003:80"
    depends_on:
      - backend
    networks:
      - matrix_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: matrix_mlm_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - admin-panel
      - user-panel
    networks:
      - matrix_network
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: matrix_mlm_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - matrix_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  matrix_network:
    driver: bridge 